### ISSUE TITLE
QueryStatistic constructor arguments

### ISSUE THREAD

**Issue by zettich** [the-tinderbox/ClickhouseClient#5]
Last changes in QueryStatistic brokes execution with error:

Too few arguments to function Tinderbox\Clickhouse\Query\QueryStatistic::__construct(), 3 passed in /home/a112445/app/vendor/the-tinderbox/clickhouse-php-client/src/Transport/HttpTransport.php on line 397 and exactly 4 expected

In source 4-th argument not marked as optional, you should add default value null to 4th argument.

**Comment by evsign** [comment]
Thanks. Hotfixed and tagged)
