### ISSUE TITLE
Problem with unnamed mapper

### ISSUE THREAD

**Issue by ivan-pomortsev** [the-tinderbox/ClickhouseClient#7]
If you're create some request which contains `?` then the client will fail with wrong bindings number error.

For example, request `$db->table('my_table')->where('field1', 'What?')->get();`
will fail with error:
```
Tinderbox\Clickhouse\Exceptions\QueryMapperException  : Wrong bindings count. Bindings found in query: 1 and given 0
```

The cause is wrong regular expression for searching bindings (`/\/?/`) – https://github.com/the-tinderbox/ClickhouseClient/blob/master/src/Query/Mapper/UnnamedMapper.php#L40

**Comment by evsign** [comment]
Thanks for the issue. I though that there, in fact, we don't even need this binding mechanism at all because there are no protocol support and we cannot validate bindings parameters in the right way, so now i considering to remove this.

**Comment by evsign** [comment]
I think i will work on it in the nearest time.

**Comment by evsign** [comment]
Recently i tagged new version of client where mappings abstraction was removed) Now all queries with `?` symbol must work fine)
